### ISSUE TITLE
.OwlBot.lock.yaml could not be updated because post processor failed

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/java-gsuite-addons#5]
```
Digest: sha256:e09db16aef633f4cae68b6eb2771b40ea01464f8db08badcd1c5197b9c623457
Status: Downloaded newer image for gcr.io/repo-automation-bots/owlbot-java@sha256:e09db16aef633f4cae68b6eb2771b40ea01464f8db08badcd1c5197b9c623457
gcr.io/repo-automation-bots/owlbot-java:latest@sha256:e09db16aef633f4cae68b6eb2771b40ea01464f8db08badcd1c5197b9c623457
Generating templates...
Traceback (most recent call last):
  File "/owlbot/src/convert-synthtool-templates.py", line 47, in <module>
    main()
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.6.12/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/owlbot/src/convert-synthtool-templates.py", line 34, in main
    node.func.value.id == "java"
AttributeError: 'Name' object has no attribute 'value'
```

Full details here:
https://console.cloud.google.com/cloud-build/builds;region=global/6466f9ca-f9ac-455f-8a40-d4135f0fef60;step=7?project=repo-automation-bots

**Comment by Neenu1995** [comment]
This repo has both owlbot.py(to manage the library) and synth.py(to manage the extra apps script protos). Owlbot was configured to convert any synth.py file it encounters and failing here because the common templates method was missing. The automatic conversion is not required since any repo migrated to owlbot will not have synth.py file and any that do are there intentionally and should not be removed.

This [PR](https://github.com/googleapis/synthtool/pull/1090) resolves this issue.
